name: flutter_project_template
description: A complete flutter project template
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5

  #router
  auto_route: ^4.0.1

  #dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.3

  #state management
  flutter_bloc: ^8.0.1

  #adaptive sizes
  adaptive_sizer:
    git:
      url: https://github.com/kishor98100/adaptive_sizer

  #data models
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  equatable: ^2.0.3

  #functional programmings
  dartz: ^0.10.1

  #network connectivity
  internet_connection_checker: ^0.0.1+4

  #network requests
  dio: ^4.0.6
  graphql: ^5.1.1
  gql_dio_link: ^0.2.2

  #env
  flutter_dotenv: ^5.0.2

  #Session
  flutter_secure_storage: ^5.0.2
  hive: ^2.2.2
  hive_flutter: ^1.1.0

  #logger
  logging: ^1.0.2

  # google fonts
  google_fonts: ^3.0.1

  #device_info
  device_info_plus: ^4.0.0

  #path provider
  path_provider: ^2.0.11


  #local database
  drift: ^1.7.0
  sqlite3_flutter_libs: ^0.5.7

  #native splash
  flutter_native_splash: ^2.2.3+1

  #image and svg renderer
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  #generators
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  hive_generator: ^1.1.3
  auto_route_generator: ^4.0.0

  #local database
  drift_dev: ^1.7.0

  #testing
  mocktail: ^0.3.0
  bloc_test: ^9.0.3

  # launcher icons
  flutter_launcher_icons: ^0.9.3

dependency_overrides:
  analyzer: ^4.1.0
  path: ^1.8.2


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - google_fonts/
    - .env-development
    - .env-staging
    - .env-production

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/localization/arb
  output_dir: lib/localization/generated


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  android_12:
    image: assets/images/splash_12.png
    icon_background_color: "#FFFFFF"